select GETDATE() as azi
select GETDATE()+1 as maine
select GETDATE()-1 as ieri
select GETDATE()+50 as [peste 50 de zile]
select YEAR(getdate())
select month(getdate()
select day(getdate())
select DATEPART(year,getdate())
select DATEPART(month,getdate())
select DATEPART(day,getdate())
select DATEPART(hour,getdate())
select DATEPART(minute,getdate())
select DATEPART(second,getdate())
select DATEPART(ms,getdate())
select DATEADD(year,5,getdate())
select DATEADD(month,4,getdate())
select DATEADD(day,7,getdate())
select DATEADD(year,5,dateadd(month,4,dateadd(day,7,getdate())))
select DATEDIFF(year,'2000-10-28',getdate())
select DATEDIFF(MONTH,'2000-10-28',getdate())
select DATEDIFF(day,'2000-10-28',getdate())

select convert(char(30),getdate(),1)
select convert(char(30),getdate(),101)
select convert(char(30),getdate(),2)
select convert(char(30),getdate(),102)
select convert(char(30),getdate(),3)
select convert(char(30),getdate(),103)
select convert(char(30),getdate(),4)
select convert(char(30),getdate(),104)
select convert(char(30),getdate(),5)
select convert(char(30),getdate(),105)
select convert(char(30),getdate(),6)
select convert(char(30),getdate(),106)
select convert(char(30),getdate(),7)
select convert(char(30),getdate(),107)
select convert(char(30),getdate(),8)
select convert(char(30),getdate(),108)
select convert(char(30),getdate(),9)
select convert(char(30),getdate(),109)
select convert(char(30),getdate(),10)
select convert(char(30),getdate(),110)
select convert(char(30),getdate(),12)
select convert(char(30),getdate(),112)