apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
spec:
  ingressClassName: nginx
  rules:
    - host: posts.com
      http:
        paths:
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000
                  # First do this:
                  # kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
                  # To be able to apply this file:
                  # k apply -f ingress-srv.yaml
                  #Remember to add this to your window/system32 "hosts" file
                  # Then visit the site using the NodePort port
                  # Example: "http://posts.com:32386/posts"